name: Meals Guide CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: buildRelease
      env: 
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace
    - name: upload Release Apks
      uses: actions/upload-artifact@v3
      #Path indicates where apk/bundle has stored after build generates them
      with:
       path: app/build/outputs/apk
       name: 'mealsGuide_apk'
    - name: cleanBuild
      run: ./gradlew clean --stacktrace
    - name: buildBundle
      env: 
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: ./gradlew bundleRelease --stacktrace
    - name: upload Bundle
      uses: actions/upload-artifact@v3
      with:
       path: app/build/outputs
       name: 'mealsGuide_bundle'
